services:
  - type: web
    name: api
    env: node
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: api
